name: "Docker Image CI"

on:
  push:
    branches: [ main ]
    tags:
      - v[1-9]+.[0-9]+.[0-9]+

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    -
      name: Set VERSION from file
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    -
      name: Build versioned image and push to local registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/reddit/gifcutterbot:${{ env.VERSION }}
    -
      name: Build latest and push to local registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/reddit/gifcutterbot:latest
    -
      name: Inspect
      run: |
        docker buildx imagetools inspect ${{ secrets.DOCKER_REGISTRY }}/reddit/gifcutterbot:latest
